---
abstract: 'Parse Indonesian phone numbers'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-PhoneNumber-ID
requires:
  Data::Clone: 0
  Log::Any: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Parse-PhoneNumber-ID/
  repository: http://github.com/sharyanto/perl-Parse-PhoneNumber-ID
version: 0.06
